--- 
- hosts: all
  vars: 
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_connection: winrm
  tasks:
  - name: Configure registry items
    win_regedit:
      path: HKLM:\Software\Microsoft\Windows\CurrentVersion\policies\system
      name: EnableLUA
      data: 1


