---
# tasks file for jritenour.vmware-cf-miq
  - name: create the VM
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      esxi_hostname: "{{ esx_host }}"
      datacenter: "{{ vc_datacenter }}"
      name: "{{ vm_name }}"
      state: poweredon
      disk:
      - size_gb: 40
        type: thin
        datastore: "{{ vc_datastore }}"
      template: "{{ template_name }}"
      networks:
      - name: VM Network
        ip: "{{ ip_addr }}"
        netmask: "{{ mask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy

  - name: Debugging instance info
    debug:
      var: deploy.instance.hw_eth0.ipaddresses[0]

  - name: add Windows server to inventory
    add_host:
      hostname: "{{ db_server }}"
      ansible_ssh_user: Administrator
      ansible_ssh_pass: "{{ win_pass }}"
      ansible_port=5985
      ansible_connection=winrm
      groupname: windows
